{
  "language": "java",
  "group": "stable",
  "dist": "precise",
  "env": "JDK_Test=\"Oracle JDK7 [ant]\"",
  "jdk": "oraclejdk7",
  "script": [
    "mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
  ],
  "os": "linux"
}